### ISSUE TITLE
Double verify the SkToPk with milagro_rust

### ISSUE THREAD

**Issue by hwwhww** [ethereum/eth2.0-deposit-cli#25]
We can use [milagro_bls_binding](https://github.com/ChihChengLiang/milagro_bls_binding) to double-verify the key generation in deposit-cli.

Pros:
- It seems all the BLS libraries have not been formally audited yet. So maybe this double-check can help us to be more confident.

Cons:
- More dependencies.
- Not sure if the binding can work well on all OSs and platforms.

/cc @ChihChengLiang

**Comment by CarlBeek** [comment]
As discussed out of band, the signatures are already verified by herumi/bis via @chainsafe/bls which means that the only portion of the signature system not verified is the SkToPk portion of `py_ecc`.

It is a simple scalar multiplication which is used in many other places (which are cross-verified with herumi due to being used during `bls.Sign()` and `bls.Verify()`). That said, I am not opposed to this additional check provided the binding works on all platforms.

**Comment by ChihChengLiang** [comment]
Ah, sorry I missed the notification of this issue. The binding currently doesn't work on Windows because the upstream use a `:` in path which Windows doesn't support. 
Happy to help if we want to support that on Windows.
