### ISSUE TITLE
Launch Pad Interface does not recognize my Deposit File

### ISSUE THREAD

**Issue by julianrmartinez** [ethereum/eth2.0-deposit-cli#85]
I followed all of the steps in the Generate Keys section. When I uploaded my Deposit Data File, the interface indicated that my file is invalid. 

Any reason why this is?
![Screen Shot 2020-08-02 at 10 15 18 AM](https://user-images.githubusercontent.com/41017290/89128580-7a070d00-d4ab-11ea-8b0f-da29407a31e8.png)

**Comment by eldavid39** [comment]
I had the same problem when I used the windows executable in interactive mode, had no issues when I generated the keys using explicit parameters, like:

(In CMD)
`deposit.exe --num_validators=<NUM_VALIDATORS> --mnemonic_language=english --chain=<CHAIN_NAME> --folder=<YOUR_FOLDER_PATH>`

I ended up doing it that way because I had this issue:
https://github.com/ethereum/eth2.0-deposit-cli/issues/70

The suggestion from @ethers on that issue provides a workaround

**Comment by AustinMichaelColeman** [comment]
I'm getting the same problem. I tried using explicit parameters and it still did not work. I was only able to work around it by using FireFox instead of Chrome. You can see here that chrome gives me the same error but FireFox does not:

<img width="943" alt="chrome-firefox-error" src="https://user-images.githubusercontent.com/12992271/90473113-fcf8ac00-e0d6-11ea-98d8-93da719d6689.png">

I tried clearing my history and cookies and disabling extensions and Chrome still gave me the same error as @julianrmartinez. 

I have attached the validator_keys
[validator_keys.zip](https://github.com/ethereum/eth2.0-deposit-cli/files/5088326/validator_keys.zip)

Some PC specs:
Windows 10 Version 1909 
Chrome Version 84.0.4147.125
Firefox version 79.0

**Comment by raunchy-mx** [comment]
It’s starting to look like Medalla doesn’t want more validators. After
finding the hidden files in “assets”, then struggling through the deposit
page, I thought I was home free until Metamask won’t load to execute the
transfer. I admit to being slow at this but am blaming that on 80 years of
hands-on efforts. Bob
